trigger:
- main  

pool:
  name: Default
  demands:
    - agent.name -equals JavierPC

variables:
  buildConfiguration: 'Release'

steps:
# Paso 1: Usar el SDK de .NET 6
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore
  displayName: 'Restaurar paquetes NuGet'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Compilar el proyecto'

- script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Ejecutar pruebas'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
