trigger:
- main  # Cambia si tu rama principal tiene otro nombre

pool:
  name: Default
  demands:
    - agent.name -equals JavierPC

variables:
  buildConfiguration: 'Release'

steps:
# Paso 1: Usar el SDK de .NET 6
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Paso 2: Restaurar dependencias
- script: dotnet restore
  displayName: 'Restaurar paquetes NuGet'

# Paso 3: Compilar el proyecto
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Compilar el proyecto'

# Paso 4: Ejecutar pruebas (opcional)
- script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Ejecutar pruebas'

# Paso 5: Publicar artefactos (opcional)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
